title: Demo Page
author: Sudhanshu Kathait
email: sudhanshukathait108@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  Testing the functionality while learning github.io for the first time
theme: minima
# social links
twitter_username: sudhanshu1111 # DO NOT include the @ character, or else the build will fail!
github_username:  skathait # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
